# Enable mouse support
setw -g mouse on

# Double tap meta key to toggle last window
bind-key C-b last-window

# Kill panes without confirm
bind -r x kill-pane

# Use VI keys
setw -g mode-keys vi

# Use VI keys to navigate panes
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# Compatibility with VIM
set -sg escape-time 0
set -g focus-events on

# Pane border color
set -g pane-border-style "fg=#5a5443"
set -g pane-active-border-style "fg=#5a5443"

# Term colors
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ',*:RGB'

# Count windows and panes from 1
set -g base-index 1
setw -g pane-base-index 1

# Status bar
set -g status-style "fg=#5b5b5b"
set -g status-position top
set -g status-right ""
set -g status-left ""
