#!/bin/sh

set -e

ln -sf "$PWD/.bash_profile" "$HOME/.bash_profile"
ln -sf "$PWD/.bashrc" "$HOME/.bashrc"
ln -sf "$PWD/.vimrc" "$HOME/.vimrc"
ln -sf "$PWD/.inputrc" "$HOME/.inputrc"
ln -sf "$PWD/.exrc" "$HOME/.exrc"

for i in foot gh git sway tmux; do
  cd $i && ./setup
  cd -
done
