let skip_defautls_vim=1
set nocompatible

" load plugins according to detected filetype.
filetype plugin indent on

" enable syntax highlighting
syntax on

" activate line relative numbers
set relativenumber

" turn info in tray or even if defautl
set ruler

" easier to see characters when `set paste` is on
set list
set listchars=tab:→\ ,nbsp:␣,trail:·,extends:⟩,precedes:⟨

" keep the terminal title updated
set laststatus=0
set icon

" prevents truncated yanks, deletes, etc.
set viminfo='20,<1000,s1000

" stop complaints about switching buffer with changes
set hidden

set linebreak

" spaces and indents
set expandtab
set autoindent
set smarttab
set smartindent
set tabstop=2
set softtabstop=2
set shiftwidth=2

set hlsearch
set incsearch
set ignorecase
map <silent> <leader><cr> :noh<cr>

set nobackup
set noswapfile
set nowritebackup

" avoid most of the 'Hit Enter ...' messages
set shortmess=aoOtI

" not a fan of bracket matching or folding
let g:loaded_matchparen=1
set noshowmatch
set foldmethod=manual

" Just the defaults, these are changed per filetype by plugins.
" Most of the utility of all of this has been superceded by the use of
" modern simplified pandoc for capturing knowledge source instead of
" arbitrary raw text files.

set formatoptions-=t   " don't auto-wrap text using text width
set formatoptions+=c   " autowrap comments using textwidth with leader
set formatoptions-=r   " don't auto-insert comment leader on enter in insert
set formatoptions-=o   " don't auto-insert comment leader on o/O in normal
set formatoptions+=q   " allow formatting of comments with gq
set formatoptions-=w   " don't use trailing whitespace for paragraphs
set formatoptions-=a   " disable auto-formatting of paragraph changes
set formatoptions-=n   " don't recognized numbered lists
set formatoptions+=j   " delete comment prefix when joining
set formatoptions-=2   " don't use the indent of second paragraph line
set formatoptions-=v   " don't use broken 'vi-compatible auto-wrapping'
set formatoptions-=b   " don't use broken 'vi-compatible auto-wrapping'
set formatoptions+=l   " long lines not broken in insert mode
set formatoptions+=m   " multi-byte character line break support
set formatoptions+=M   " don't add space before or after multi-byte char
set formatoptions-=B   " don't add space between two multi-byte chars in join 
set formatoptions+=1   " don't break a line after a one-letter word

" faster scrolling
set ttyfast

" start at last place you were editing
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

