let skip_defautls_vim=1
set nocompatible

" not a fan of these plugins
let g:loaded_netrw=1
let g:loaded_netrwPlugin=1
let g:loaded_matchparen=1

filetype plugin indent on
colorscheme habamax
syntax on

set viminfofile=~/.vim/viminfo
set numberwidth=1
set noshowmode
set relativenumber
set expandtab
set autoindent
set smarttab
set smartindent
set tabstop=4
set shiftwidth=4
set linebreak
set wrap
set nobackup
set noswapfile
set nowritebackup

