# Solve problems with <esc> delay and nvim
set -sg escape-time 10

# Enable mouse mode
set -g mouse on

# Configs for a more minimal status bar
set -g status-right ""
set -g status-left ""
set -g status-style "fg=#5b5b5b"
set -g status-position top

# Count windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Reload configuration with <prefix>r
bind r source-file ~/.config/tmux/tmux.conf

# Remove the pane active border color
set -g pane-active-border fg=white

# According to neovim checkhealth
set-option -sa terminal-features ",alacritty:RGB"
set-option -g focus-events on

