# Use VI keys.
setw -g mode-keys vi
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# Pane border color.
set -g pane-border-style "fg=#111111"
set -g pane-active-border-style "fg=#111111"

# Disable status bar.
set -g status off

# Kill panes without confirm.
bind -r x kill-pane

