# Use vi keys.
setw -g mode-keys vi
set -g status-keys vi
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# Change default meta key.
unbind C-b
unbind C-a
set -g prefix C-a

# Pane border.
set -g pane-border-style "fg=#111111"
set -g pane-active-border-style "fg=#111111"

# Term colors.
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ',*:RGB'

# Disable status bar.
set -g status off

# Kill panes without confirm.
bind -r x kill-pane

