# Foot configuration

# Font style and size
font=JetBrainsMono Nerd Font:size=14

# Padding
# pad=5x5

[mouse]
hide-when-typing=yes

# Colors
[colors]
background=1e1e1e
foreground=d4d4d4

# Normal/regular colors (color pallete 0-7)
regular0=333333
regular1=4c4c4c
regular2=666666
regular3=999999
regular4=b2b2b2
regular5=cccccc
regular6=e5e5e5
regular7=ffffff

# Bright colors (color palette 8-15)
bright0=333333
bright1=4c4c4c
bright2=666666
bright3=999999
bright4=b2b2b2
bright5=cccccc
bright6=e5e5e5
bright7=ffffff

