abbr --add e 'exit'
abbr --add c 'clear'
abbr --add mv 'mv -i'
abbr --add cp 'cp -Ri'
abbr --add du 'du -ch'
abbr --add vi '$EDITOR'
abbr --add rm 'rm -rvI'
abbr --add ga 'git add'
abbr --add gp 'git push'
abbr --add gd 'git diff'
abbr --add free 'free -h'
abbr --add gs 'git status'
abbr --add mkdir 'mkdir -pv'
abbr --add t 'bat ~/.todo.md'
abbr --add gw 'gh repo view --web'
abbr --add todo '$EDITOR ~/.todo.md'
abbr --add gl 'git log --graph --decorate --oneline'
abbr --add l 'eza --long --all --all --classify --git --git-repos --header --icons=auto --color=auto --group-directories-first'
