abbr --add e 'exit'
abbr --add c 'clear'
abbr --add vi '$EDITOR'
abbr --add gs 'git status'
abbr --add tree 'eza --tree'
abbr --add todo '$EDITOR ~/.todo.md'
abbr --add cat 'bat --theme-dark=gruvbox-dark'
abbr --add gl 'git log --graph --decorate --oneline'
abbr --add t 'bat --theme-dark=gruvbox-dark ~/.todo.md'
abbr --add btm 'btm --tree --disable_click --hide_table_gap --celsius'
abbr --add ls 'eza --long --all --all --classify --git --git-repos --header --icons=auto --color=auto --group-directories-first'
