abbr --add e 'exit'
abbr --add c 'clear'
abbr --add vi '$EDITOR'
abbr --add gs 'git status'
abbr --add tree 'eza --tree'
abbr --add todo '$EDITOR ~/.todo.md'
abbr --add gl 'git log --graph --decorate --oneline'
abbr --add ls 'eza --long --all --all --classify --git --git-repos --header --icons=auto --color=auto --group-directories-first'
