#!/bin/sh

if ! command -v go >/dev/null 2>&1; then
  echo "go command is not available. Please install it first."
  exit 1
fi

if command -v mods >/dev/null 2>&1; then
  echo "mods is already installed"
else
  echo "Installing mods..."
  go install github.com/charmbracelet/mods@latest
fi
