#!/usr/bin/env bash

if ! command -v shellcheck > /dev/null 2>&1; then
  echo "Error: shellcheck is not installed"
  exit 1
fi

# Find and iterate over all regular files in the top-level directory
find . -maxdepth 1 -type f | while read -r file; do
  if [ -x "$file" ]; then
    shellcheck "$file"
  else
    echo "$file is not executable."
  fi
done
