#!/bin/sh
#
# Create a new script in my scripts collection

name=$1

if [ -z "$name" ]; then
  echo "No name provided. Exiting."
  exit 1
fi

cd "$SCRIPTS" || exit
touch "$name" && chmod u+x "$name"
{
  echo "#!/bin/sh"
  echo "#"
  echo "#"
} >> "$name"

"$EDITOR" "$name"
