#!/usr/bin/env bash

if command -v &>/dev/null; then
$EDITOR $(fzf --style=full \
  --preview "bat --color=always --style=numbers --line-range=:500 {}" \
  --bind 'focus:transform-header:file \
  --brief {}')
else
  echo "fzf not available"
fi
