import = [".config/alacritty/themes/vscode.toml"] # Import theme

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
dynamic_padding = true # Fix problems with padding
startup_mode = "Maximized"

